using System.ComponentModel;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace Telahi.WPF
{
	/// <summary>
	/// Interaction logic for MainWindow.xaml
	/// </summary>
	public partial class MainWindow : Window
	{
		 //-non Static(this member)
		 //Can be Changed
		 //Changing only in constractor(any)
	//	readonly string PREFIXTITLE = "TelHai Course";

		//--Static
		//Fixed Cant Changed Once Initialized
		//const string PREFIXTITLE2 = "TelHai Course";

		//public MainWindow(string title)
  //      {
		//	PREFIXTITLE += "_";
		//	this.Title = PREFIXTITLE+title;

  //      }


        public MainWindow()
		{
			//Generate Objects According XAML
			InitializeComponent();
			this.Title = "TelHai Course";
			Button b3 = new Button() {Content="Generated By Code", FontSize=35,Name="Btn3" };
			Canvas.SetLeft(b3, 300);
			Canvas.SetTop(b3, 300);
			this.cnavasRoot.Children.Add(b3);
			
			b3.Click += Button_Click;
	  	//b3.Click += Button2_Click;


		}

		private void Button_Click(object sender, RoutedEventArgs e)
		{
		    if (sender is Button btn) 
			{
				MessageBox.Show(btn.Name, "Buttn");
				this.Title += "_"+btn.Name;
			}
		
			

		}
		private void Button2_Click(object sender, RoutedEventArgs e)
		{


			MessageBox.Show("Button2_Click");

		}

		protected override void OnClosing(CancelEventArgs e)
		{
			base.OnClosing(e);
			//e.Cancel = true;
			//Save data
			//And Check With User That the Windoe Is about closing
		}




	}
}